language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules" # This will tell Travis CI to cache the dependencies
# whitelist
branches:
  only:
    - master
    - development
    - travis
    - rules
jobs:
  include:
    - stage: Run tests
      name: "Run unit and integration tests"
      script: npm test # Here you could also run the build step of your application
    - stage: Deploy to now
      name: "Deploy to Zeit now"
      script: skip
      before_deploy: npm install now --no-save # Install Now CLI on Travis
      deploy:
        - provider: script # Run a custom deployment script which we will define below
          script: now --public --token $NOW_TOKEN && now alias --token $NOW_TOKEN
          skip_cleanup: true
          on:
            all_branches: true
            master: false
        - provider: script
          script: now --public --token $NOW_TOKEN && now alias --token $NOW_TOKEN
          skip_cleanup: true
          on:
            master: true
      after_deploy:
        now alias blogilista10.now.sh -r rules.json --token $NOW_TOKEN
        #now rm full-stack-open-2018-blogilista --token $NOW_TOKEN --safe --yes --public
      - stage: Cleanup
        name: "Remove old deployments from Zeit now"
        script: now rm full-stack-open-2018-blogilista --token $NOW_TOKEN --safe --yes --public  