language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules" # This will tell Travis CI to cache the dependencies
# whitelist
branches:
  only:
    - master
    - development
    - travis
jobs:
  include:
    - #stage: Run tests
      #name: "Run unit and integration tests"
      #script: npm test # Here you could also run the build step of your application
      #script: echo "Mocking test runs"
    - stage: Deploy to now
      name: "Deploy to Zeit now"
      install: 
      - npm install now --no-save # Install Now CLI on Travis
      #- npm install # all dependencies defined in package.json
      script: skip
        #now --public -e PORT=3003 --token $NOW_TOKEN
        #now --public -e DEVELOPMENT_DB=@ds143971.mlab.com:43971/blogilista --token $NOW_TOKEN
      #before_deploy: npm install now --no-save # Install Now CLI on Travis
      deploy:
        - provider: script # Run a custom deployment script which we will define below
          #script: echo "Starting now --public ..."
          #script: now --public --token $NOW_TOKEN
          script: now --public --token $NOW_TOKEN && now alias --token $NOW_TOKEN
          skip_cleanup: true
          on:
            all_branches: true
            master: false
        #- provider: script
        #  script: now --public --token $NOW_TOKEN && now alias --token $NOW_TOKEN
        #  skip_cleanup: true
        #  on:
        #    master: true
      after_deploy:
        echo "Remove old deployments ..."
      # script: now rm full-stack-open-2018-blogilista --token $NOW_TOKEN --safe --yes --public