language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules" # This will tell Travis CI to cache the dependencies
# whitelist
branches:
  only:
    - master
    - dev-travis
jobs:
  include:
    - stage: Run tests
      script: npm test # Here you could also run the build step of your application
    - stage: Install now
      script: npm install now --no-save # Install Now CLI on Travis
    - stage: Setup environment
      name: "Setup environment variables to now"
  	  # Set secrets to environment variables
      script: now -e DbUserPuhLuet=@dbuserpuhluet-key
	    script: now -e DbPasswordPuhLuet=@dbpasswordpuhluet-key
	    script: now -e SECRET=@secret
  	  # Set other environment variables
	    script: now -e PRODUCTION_DB=@ds143971.mlab.com:43971/blogilista_prod
	    script: now -e DEVELOPMENT_DB=@ds143971.mlab.com:43971/blogilista
	    script: now -e PORT=3003
	    script: now -e TEST_PORT=0
    - stage: Deploy to now
      script: skip
      deploy:
        - provider: script # Run a custom deployment script which we will define below
          script: now --public --token $NOW_TOKEN && now alias --token $NOW_TOKEN
          skip_cleanup: true
          on:
            all_branches: true
            master: false
        - provider: script
          script: now --public --token $NOW_TOKEN && now alias --token $NOW_TOKEN
          skip_cleanup: true
          on:
            master: true