language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules" # This will tell Travis CI to cache the dependencies
# whitelist
branches:
  only:
    - master
    - development
jobs:
  include:
    - stage: Run tests
      name: "Run unit and integration tests"
      script: npm test # Here you could also run the build step of your application
    - stage: Deploy to now
      name: "Deploy to Zeit now"
      install: 
      - npm install now --no-save # Install Now CLI on Travis
      script: 
        now --public -e PORT=3003 --token $NOW_TOKEN
        #now --public -e DEVELOPMENT_DB=@ds143971.mlab.com:43971/blogilista --token $NOW_TOKEN
      deploy:
        - provider: script # Run a custom deployment script which we will define below
          script: now --public --token $NOW_TOKEN && now alias --token $NOW_TOKEN
          skip_cleanup: true
          on:
            all_branches: true
            master: false
        - provider: script
          script: now --public --token $NOW_TOKEN && now alias --token $NOW_TOKEN
          skip_cleanup: true
          on:
            master: true