language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules" # This will tell Travis CI to cache the dependencies
# whitelist
branches:
  only:
    - master
    - dev-travis
jobs:
  include:
    - stage: Run tests
      script: npm test # Here you could also run the build step of your application
    - stage: Install now
      name: "Install now Zeit CLI to Travis"
      script: npm install now --no-save # Install Now CLI on Travis
   - stage: Deploy to now
      script: skip
      deploy:
        - provider: script # Run a custom deployment script which we will define below
          script: now --public --token $NOW_TOKEN && now alias --token $NOW_TOKEN
          skip_cleanup: true
          on:
            all_branches: true
            master: false
        - provider: script
          script: now --public --token $NOW_TOKEN && now alias --token $NOW_TOKEN
          skip_cleanup: true
          on:
            master: true