POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhc3VubWFhIiwiaWQiOiI1YjY3MzRiMDkyZDQ2ZTJlMzAwZjk3ZjIiLCJpYXQiOjE1MzM0OTAzNjl9.DrEf0je-8oeA_g-zcqrkaNQ6m_9yYDC0i5ELU8onBcU

{
    "title": "Kia's blog69",
    "author": "Kimmo Lehtinen",
    "url": "http://localhost:3003/api/blogs",
    "likes": "69"
}